// Automatically generated by scripts/sync-extensions.js from flyclip-extensions repository.
// DO NOT EDIT MANUALLY. Modify Config.yaml in flyclip-extensions instead.

export interface ExtensionItem {
  id: string;
  name: string;
  nameZh?: string;
  nameEn?: string;
  category: 'translation' | 'search_ai' | 'text_tools' | 'developer' | 'shopping';
  icon: string;
  description: string;
  descriptionZh: string;
  hasOptions: boolean;
  optionsCount?: number;
  type: 'url' | 'js' | 'powershell' | 'keys';
  configYaml: string;
}

const EXTENSION_PACKAGE_MAP: Record<string, string> = {
  "com.flyclip.extension.amazon": "Amazon",
  "com.flyclip.extension.baidu-search": "BaiduSearch",
  "com.flyclip.extension.baidu-translate": "BaiduTranslate",
  "com.flyclip.extension.base64": "Base64",
  "com.flyclip.extension.bilibili-search": "BilibiliSearch",
  "com.flyclip.extension.bing-search": "BingSearch",
  "com.flyclip.extension.calculate": "Calculate",
  "com.flyclip.extension.case-converter": "CaseConverter",
  "com.flyclip.extension.chatgpt": "ChatGPT",
  "com.flyclip.extension.claude": "Claude",
  "com.flyclip.extension.cut": "Cut",
  "com.flyclip.extension.deepl-translate": "DeepLTranslate",
  "com.flyclip.extension.deepseek": "DeepSeek",
  "com.flyclip.extension.douban-search": "Douban",
  "com.flyclip.extension.duckduckgo": "DuckDuckGo",
  "com.flyclip.extension.full-half-width": "FullHalfWidth",
  "com.flyclip.extension.github-search": "GitHubSearch",
  "com.flyclip.extension.google-search": "GoogleSearch",
  "com.flyclip.extension.google-translate": "GoogleTranslate",
  "com.flyclip.extension.hash-generator": "HashGenerator",
  "com.flyclip.extension.html-encode": "HTMLEncode",
  "com.flyclip.extension.imdb": "IMDb",
  "com.flyclip.extension.ip-lookup": "IPLookup",
  "com.flyclip.extension.jd-search": "JD",
  "com.flyclip.extension.join-lines": "JoinLines",
  "com.flyclip.extension.json-formatter": "JSONFormatter",
  "com.flyclip.extension.markdown-tools": "MarkdownTools",
  "com.flyclip.extension.mdn-web-docs": "MDNWebDocs",
  "com.flyclip.extension.pot-desktop": "PotTranslate",
  "com.flyclip.extension.regex101": "RegexTest",
  "com.flyclip.extension.remove-spaces": "RemoveSpaces",
  "com.flyclip.extension.iconify-search": "SearchIcons",
  "com.flyclip.extension.sort-lines": "SortLines",
  "com.flyclip.extension.stranslate": "STranslate",
  "com.flyclip.extension.taobao-search": "Taobao",
  "com.flyclip.extension.text-statistics": "TextStatistics",
  "com.flyclip.extension.timestamp-converter": "TimestampConvert",
  "com.flyclip.extension.urban-dictionary": "UrbanDictionary",
  "com.flyclip.extension.url-encode": "URLEncode",
  "com.flyclip.extension.wikipedia": "Wikipedia",
  "com.flyclip.extension.youdao-dict": "YoudaoTranslate",
  "com.flyclip.extension.youtube-search": "YouTubeSearch",
  "com.flyclip.extension.zhihu-search": "ZhihuSearch",
};

export function getExtensionPackageName(id: string): string {
  return EXTENSION_PACKAGE_MAP[id] || id.split('.').pop() || 'Extension';
}

export const EXTENSIONS_DATA: ExtensionItem[] = [
  {
    id: "com.flyclip.extension.amazon",
    name: "Amazon",
    nameZh: "亚马逊商城",
    nameEn: "Amazon",
    category: "shopping",
    icon: "iconify:simple-icons:amazon",
    description: "Search Amazon worldwide with site selection.",
    descriptionZh: "在全球 Amazon 亚马逊商城（美/中/日/英/德）搜索商品。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Amazon\n  zh-CN: 亚马逊商城\ndescription:\n  en: Search Amazon worldwide with site selection.\n  zh-CN: 在全球 Amazon 亚马逊商城（美/中/日/英/德）搜索商品。\nidentifier: com.flyclip.extension.amazon\nicon: iconify:simple-icons:amazon\noptions:\n  - identifier: site\n    label:\n      en: Amazon Store\n      zh: 亚马逊商城站点\n    type: multiple\n    values:\n      - amazon.com\n      - amazon.cn\n      - amazon.co.jp\n      - amazon.co.uk\n      - amazon.de\n    value labels:\n      - US (amazon.com)\n      - 中国 (amazon.cn)\n      - 日本 (amazon.co.jp)\n      - 英国 (amazon.co.uk)\n      - 德国 (amazon.de)\n    default value: amazon.com\n\nactions:\n  - title: Amazon\n    url: https://www.{flyclip option site}/s?k=***\n    spaces as plus: true\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.baidu-search",
    name: "Baidu Search",
    nameZh: "百度搜索",
    nameEn: "Baidu Search",
    category: "search_ai",
    icon: "iconify:simple-icons:baidu",
    description: "Search with Baidu Search Engine.",
    descriptionZh: "使用百度搜索选中的关键词。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Baidu Search\n  zh-CN: 百度搜索\ndescription:\n  en: Search with Baidu Search Engine.\n  zh-CN: 使用百度搜索选中的关键词。\nidentifier: com.flyclip.extension.baidu-search\nicon: iconify:simple-icons:baidu\nactions:\n  - title: 百度\n    url: https://www.baidu.com/s?wd=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.baidu-translate",
    name: "Baidu Translate",
    nameZh: "百度翻译",
    nameEn: "Baidu Translate",
    category: "translation",
    icon: "iconify:simple-icons:baidu",
    description: "Translate text with Baidu Translate.",
    descriptionZh: "使用百度翻译引擎翻译选中文本。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Baidu Translate\n  zh-CN: 百度翻译\ndescription:\n  en: Translate text with Baidu Translate.\n  zh-CN: 使用百度翻译引擎翻译选中文本。\nidentifier: com.flyclip.extension.baidu-translate\nicon: iconify:simple-icons:baidu\noptions:\n  - identifier: target_lang\n    label:\n      en: Target Language\n      zh: 目标语言\n    type: multiple\n    values:\n      - zh\n      - en\n      - jp\n      - kor\n      - fra\n      - de\n      - spa\n      - ru\n    value labels:\n      - 中文 (zh)\n      - 英语 (en)\n      - 日语 (jp)\n      - 韩语 (kor)\n      - 法语 (fra)\n      - 德语 (de)\n      - 西班牙语 (spa)\n      - 俄语 (ru)\n    default value: zh\n\nactions:\n  - title: 百度翻译\n    url: https://fanyi.baidu.com/#auto/{flyclip option target_lang}/{flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.base64",
    name: "Base64",
    nameZh: "Base64 编解码",
    nameEn: "Base64",
    category: "text_tools",
    icon: "B64",
    description: "Encode or decode Base64 strings with optional URL-safe mode.",
    descriptionZh: "Base64 快速编码与解码，支持 URL 安全模式开关。",
    hasOptions: true,
    optionsCount: 1,
    type: "js",
    configYaml: "name:\n  en: Base64\n  zh-CN: Base64 编解码\ndescription:\n  en: Encode or decode Base64 strings with optional URL-safe mode.\n  zh-CN: Base64 快速编码与解码，支持 URL 安全模式开关。\nidentifier: com.flyclip.extension.base64\nicon: B64\noptions:\n  - identifier: url_safe\n    label:\n      en: URL-safe Base64 (- and _)\n      zh: URL 安全模式 (使用 - 与 _)\n    type: boolean\n    default value: false\n\nactions:\n  - title: Base64 编码\n    identifier: encode\n    javascript: |\n      const str = flyclip.input.text;\n      let b64 = btoa(unescape(encodeURIComponent(str)));\n      if (flyclip.options.url_safe === \"1\" || flyclip.options.url_safe === true) {\n        b64 = b64.replace(/\\+/g, '-').replace(/\\//g, '_').replace(/=+$/, '');\n      }\n      return b64;\n    requirements: [text]\n    after: paste-result\n\n  - title: Base64 解码\n    identifier: decode\n    javascript: |\n      let s = flyclip.input.text.trim();\n      if (flyclip.options.url_safe === \"1\" || flyclip.options.url_safe === true) {\n        s = s.replace(/-/g, '+').replace(/_/g, '/');\n        while (s.length % 4 !== 0) {\n          s += '=';\n        }\n      }\n      try {\n        return decodeURIComponent(escape(atob(s)));\n      } catch (e) {\n        return \"[Base64 解码错误: 格式不合法]\";\n      }\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.bilibili-search",
    name: "Bilibili Search",
    nameZh: "哔哩哔哩",
    nameEn: "Bilibili Search",
    category: "search_ai",
    icon: "iconify:simple-icons:bilibili",
    description: "Search anime, tutorials, and creators on Bilibili.",
    descriptionZh: "在哔哩哔哩搜索精选视频、教程与UP主。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Bilibili Search\n  zh-CN: 哔哩哔哩\ndescription:\n  en: Search anime, tutorials, and creators on Bilibili.\n  zh-CN: 在哔哩哔哩搜索精选视频、教程与UP主。\nidentifier: com.flyclip.extension.bilibili-search\nicon: iconify:simple-icons:bilibili\nactions:\n  - title: 哔哩哔哩\n    url: https://search.bilibili.com/all?keyword=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.bing-search",
    name: "Bing Search",
    nameZh: "必应搜索",
    nameEn: "Bing Search",
    category: "search_ai",
    icon: "iconify:simple-icons:microsoftbing",
    description: "Search with Microsoft Bing.",
    descriptionZh: "使用微软必应 Bing 搜索选中文本。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Bing Search\n  zh-CN: 必应搜索\ndescription:\n  en: Search with Microsoft Bing.\n  zh-CN: 使用微软必应 Bing 搜索选中文本。\nidentifier: com.flyclip.extension.bing-search\nicon: iconify:simple-icons:microsoftbing\nactions:\n  - title: Bing\n    url: https://www.bing.com/search?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.calculate",
    name: "Calculate",
    nameZh: "即时数学计算",
    nameEn: "Calculate",
    category: "developer",
    icon: "=?",
    description: "Evaluate math expressions instantly (e.g. 128*1024, (50+20)/3).",
    descriptionZh: "即时计算选中的数学表达式并显示结果。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Calculate\n  zh-CN: 即时数学计算\ndescription:\n  en: Evaluate math expressions instantly (e.g. 128*1024, (50+20)/3).\n  zh-CN: 即时计算选中的数学表达式并显示结果。\nidentifier: com.flyclip.extension.calculate\nicon: \"=?\"\nactions:\n  - title: 计算结果\n    identifier: eval\n    javascript: |\n      const expr = flyclip.input.text.trim();\n      try {\n        const res = Function(`'use strict'; return (${expr})`)();\n        return `${expr} = ${res}`;\n      } catch (e) {\n        return \"[计算出错: 表达式无效]\";\n      }\n    requirements: [text]\n    after: show-result"
  },
  {
    id: "com.flyclip.extension.case-converter",
    name: "Case Converter",
    nameZh: "大小写转换",
    nameEn: "Case Converter",
    category: "text_tools",
    icon: "Aa",
    description: "Convert text between UPPER, lower, Title, camelCase, snake_case, kebab-case.",
    descriptionZh: "全能大小写命名风格转换（大写/小写/词首/小驼峰/下划线/连字符）。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Case Converter\n  zh-CN: 大小写转换\ndescription:\n  en: Convert text between UPPER, lower, Title, camelCase, snake_case, kebab-case.\n  zh-CN: 全能大小写命名风格转换（大写/小写/词首/小驼峰/下划线/连字符）。\nidentifier: com.flyclip.extension.case-converter\nicon: Aa\nactions:\n  - title: 大写 (UPPER)\n    identifier: uppercase\n    javascript: return flyclip.input.text.toUpperCase();\n    requirements: [text]\n    after: paste-result\n\n  - title: 小写 (lower)\n    identifier: lowercase\n    javascript: return flyclip.input.text.toLowerCase();\n    requirements: [text]\n    after: paste-result\n\n  - title: 词首大写 (Title)\n    identifier: titlecase\n    javascript: return flyclip.input.text.replace(/\\w\\S*/g, (w) => w.charAt(0).toUpperCase() + w.substr(1).toLowerCase());\n    requirements: [text]\n    after: paste-result\n\n  - title: 驼峰 (camelCase)\n    identifier: camelcase\n    javascript: |\n      const words = flyclip.input.text.split(/[^a-zA-Z0-9]+/).filter(Boolean);\n      if (words.length === 0) return flyclip.input.text;\n      const first = words[0].toLowerCase();\n      const rest = words.slice(1).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('');\n      return first + rest;\n    requirements: [text]\n    after: paste-result\n\n  - title: 下划线 (snake_case)\n    identifier: snakecase\n    javascript: |\n      return flyclip.input.text\n        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')\n        .replace(/[^a-zA-Z0-9]+/g, '_')\n        .replace(/^_+|_+$/g, '')\n        .toLowerCase();\n    requirements: [text]\n    after: paste-result\n\n  - title: 连字符 (kebab-case)\n    identifier: kebabcase\n    javascript: |\n      return flyclip.input.text\n        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')\n        .replace(/[^a-zA-Z0-9]+/g, '-')\n        .replace(/^-+|-+$/g, '')\n        .toLowerCase();\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.chatgpt",
    name: "ChatGPT",
    nameZh: "ChatGPT",
    nameEn: "ChatGPT",
    category: "search_ai",
    icon: "iconify:simple-icons:openai",
    description: "Ask ChatGPT or analyze text with OpenAI.",
    descriptionZh: "快速将选中文本发送给 ChatGPT 进行提问或智能分析。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: ChatGPT\n  zh-CN: ChatGPT\ndescription:\n  en: Ask ChatGPT or analyze text with OpenAI.\n  zh-CN: 快速将选中文本发送给 ChatGPT 进行提问或智能分析。\nidentifier: com.flyclip.extension.chatgpt\nicon: iconify:simple-icons:openai\nactions:\n  - title: ChatGPT\n    url: https://chatgpt.com/?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.claude",
    name: "Claude",
    nameZh: "Claude",
    nameEn: "Claude",
    category: "search_ai",
    icon: "iconify:simple-icons:anthropic",
    description: "Send selected text to Anthropic Claude AI.",
    descriptionZh: "发送选中文本给 Anthropic Claude 对话交互。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Claude\n  zh-CN: Claude\ndescription:\n  en: Send selected text to Anthropic Claude AI.\n  zh-CN: 发送选中文本给 Anthropic Claude 对话交互。\nidentifier: com.flyclip.extension.claude\nicon: iconify:simple-icons:anthropic\nactions:\n  - title: Claude\n    url: https://claude.ai/new?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.cut",
    name: "Cut",
    nameZh: "剪切",
    nameEn: "Cut",
    category: "text_tools",
    icon: "scissors",
    description: "Cut selected text to clipboard.",
    descriptionZh: "剪切所选文本到剪贴板。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Cut\n  zh-CN: 剪切\ndescription:\n  en: Cut selected text to clipboard.\n  zh-CN: 剪切所选文本到剪贴板。\nidentifier: com.flyclip.extension.cut\nicon: scissors\nactions:\n  - title:\n      en: Cut\n      zh-CN: 剪切\n    icon: scissors\n    command: cut\n    requirements: [cut]"
  },
  {
    id: "com.flyclip.extension.deepl-translate",
    name: "DeepL Translate",
    nameZh: "DeepL 翻译",
    nameEn: "DeepL Translate",
    category: "translation",
    icon: "iconify:simple-icons:deepl",
    description: "High-accuracy neural machine translation with DeepL.",
    descriptionZh: "使用 DeepL 神经网络高质量翻译选中文本。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: DeepL Translate\n  zh-CN: DeepL 翻译\ndescription:\n  en: High-accuracy neural machine translation with DeepL.\n  zh-CN: 使用 DeepL 神经网络高质量翻译选中文本。\nidentifier: com.flyclip.extension.deepl-translate\nicon: iconify:simple-icons:deepl\noptions:\n  - identifier: target_lang\n    label:\n      en: Target Language\n      zh: 目标语言\n    type: multiple\n    values:\n      - zh\n      - en\n      - ja\n      - de\n      - fr\n      - es\n      - ru\n      - ko\n    value labels:\n      - 中文 (zh)\n      - English (en)\n      - 日本語 (ja)\n      - Deutsch (de)\n      - Français (fr)\n      - Español (es)\n      - Русский (ru)\n      - 한국어 (ko)\n    default value: zh\n\nactions:\n  - title: DeepL\n    url: https://www.deepl.com/translator#auto/{flyclip option target_lang}/{flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.deepseek",
    name: "DeepSeek",
    nameZh: "DeepSeek 深度求索",
    nameEn: "DeepSeek",
    category: "search_ai",
    icon: "DS",
    description: "Ask DeepSeek AI with selected text.",
    descriptionZh: "发送选中文本给 DeepSeek 深度求索 AI 助手分析。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: DeepSeek\n  zh-CN: DeepSeek 深度求索\ndescription:\n  en: Ask DeepSeek AI with selected text.\n  zh-CN: 发送选中文本给 DeepSeek 深度求索 AI 助手分析。\nidentifier: com.flyclip.extension.deepseek\nicon: DS\nactions:\n  - title: DeepSeek\n    url: https://chat.deepseek.com/?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.douban-search",
    name: "Douban Search",
    nameZh: "豆瓣搜索",
    nameEn: "Douban Search",
    category: "shopping",
    icon: "iconify:simple-icons:douban",
    description: "Search movies, books, and music on Douban.",
    descriptionZh: "在豆瓣搜索高分电影、热门图书与音乐条目。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Douban Search\n  zh-CN: 豆瓣搜索\ndescription:\n  en: Search movies, books, and music on Douban.\n  zh-CN: 在豆瓣搜索高分电影、热门图书与音乐条目。\nidentifier: com.flyclip.extension.douban-search\nicon: iconify:simple-icons:douban\noptions:\n  - identifier: cat\n    label:\n      en: Category\n      zh: 搜索分类\n    type: multiple\n    values:\n      - \"1001\"\n      - \"1002\"\n      - \"1003\"\n    value labels:\n      - 电影 (Movie)\n      - 图书 (Book)\n      - 音乐 (Music)\n    default value: \"1001\"\n\nactions:\n  - title: 豆瓣\n    url: https://www.douban.com/search?cat={flyclip option cat}&q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.duckduckgo",
    name: "DuckDuckGo",
    nameZh: "DuckDuckGo",
    nameEn: "DuckDuckGo",
    category: "search_ai",
    icon: "iconify:simple-icons:duckduckgo",
    description: "Privacy search with DuckDuckGo.",
    descriptionZh: "使用 DuckDuckGo 隐私无追踪搜索引擎。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: DuckDuckGo\n  zh-CN: DuckDuckGo\ndescription:\n  en: Privacy search with DuckDuckGo.\n  zh-CN: 使用 DuckDuckGo 隐私无追踪搜索引擎。\nidentifier: com.flyclip.extension.duckduckgo\nicon: iconify:simple-icons:duckduckgo\nactions:\n  - title: DDG\n    url: https://duckduckgo.com/?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.full-half-width",
    name: "Full/Half Width",
    nameZh: "全角半角转换",
    nameEn: "Full/Half Width",
    category: "text_tools",
    icon: "全半",
    description: "Convert between Full-width and Half-width characters.",
    descriptionZh: "全角标点字符与半角英文字符双向转换。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Full/Half Width\n  zh-CN: 全角半角转换\ndescription:\n  en: Convert between Full-width and Half-width characters.\n  zh-CN: 全角标点字符与半角英文字符双向转换。\nidentifier: com.flyclip.extension.full-half-width\nicon: 全半\nactions:\n  - title: 全角转半角 (Full to Half)\n    identifier: to_half\n    javascript: |\n      let str = \"\";\n      for (let i = 0; i < flyclip.input.text.length; i++) {\n        let code = flyclip.input.text.charCodeAt(i);\n        if (code === 12288) {\n          str += String.fromCharCode(32);\n        } else if (code >= 65281 && code <= 65374) {\n          str += String.fromCharCode(code - 65248);\n        } else {\n          str += flyclip.input.text[i];\n        }\n      }\n      return str;\n    requirements: [text]\n    after: paste-result\n\n  - title: 半角转全角 (Half to Full)\n    identifier: to_full\n    javascript: |\n      let str = \"\";\n      for (let i = 0; i < flyclip.input.text.length; i++) {\n        let code = flyclip.input.text.charCodeAt(i);\n        if (code === 32) {\n          str += String.fromCharCode(12288);\n        } else if (code >= 33 && code <= 126) {\n          str += String.fromCharCode(code + 65248);\n        } else {\n          str += flyclip.input.text[i];\n        }\n      }\n      return str;\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.github-search",
    name: "GitHub Search",
    nameZh: "GitHub 搜索",
    nameEn: "GitHub Search",
    category: "search_ai",
    icon: "iconify:simple-icons:github",
    description: "Search repositories, code, and issues on GitHub.",
    descriptionZh: "在 GitHub 搜索开源仓库、源码片段或 Issue 问题。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: GitHub Search\n  zh-CN: GitHub 搜索\ndescription:\n  en: Search repositories, code, and issues on GitHub.\n  zh-CN: 在 GitHub 搜索开源仓库、源码片段或 Issue 问题。\nidentifier: com.flyclip.extension.github-search\nicon: iconify:simple-icons:github\noptions:\n  - identifier: search_type\n    label:\n      en: Search Type\n      zh: 搜索类型\n    type: multiple\n    values:\n      - repositories\n      - code\n      - issues\n      - commits\n      - users\n    value labels:\n      - Repositories (代码仓库)\n      - Code (代码)\n      - Issues (工单/问题)\n      - Commits (提交记录)\n      - Users (开发者)\n    default value: repositories\n\nactions:\n  - title: GitHub\n    url: https://github.com/search?q={flyclip text}&type={flyclip option search_type}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.google-search",
    name: "Google Search",
    nameZh: "Google 搜索",
    nameEn: "Google Search",
    category: "search_ai",
    icon: "iconify:simple-icons:google",
    description: "Search the web with Google Search.",
    descriptionZh: "使用 Google 搜索选中的关键词。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Google Search\n  zh-CN: Google 搜索\ndescription:\n  en: Search the web with Google Search.\n  zh-CN: 使用 Google 搜索选中的关键词。\nidentifier: com.flyclip.extension.google-search\nicon: iconify:simple-icons:google\noptions:\n  - identifier: site\n    label:\n      en: Google Domain\n      zh: Google 搜索域名\n    type: multiple\n    values:\n      - google.com\n      - google.com.hk\n      - google.co.jp\n      - google.co.uk\n    value labels:\n      - google.com (Global)\n      - google.com.hk (Hong Kong)\n      - google.co.jp (Japan)\n      - google.co.uk (UK)\n    default value: google.com\n\nactions:\n  - title: Google\n    url: https://www.{flyclip option site}/search?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.google-translate",
    name: "Google Translate",
    nameZh: "Google 翻译",
    nameEn: "Google Translate",
    category: "translation",
    icon: "iconify:simple-icons:googletranslate",
    description: "Translate selected text with Google Translate worldwide.",
    descriptionZh: "使用 Google 翻译选中文本，支持多站点切换与目标语言设定。",
    hasOptions: true,
    optionsCount: 2,
    type: "url",
    configYaml: "name:\n  en: Google Translate\n  zh-CN: Google 翻译\ndescription:\n  en: Translate selected text with Google Translate worldwide.\n  zh-CN: 使用 Google 翻译选中文本，支持多站点切换与目标语言设定。\nidentifier: com.flyclip.extension.google-translate\nicon: iconify:simple-icons:googletranslate\noptions:\n  - identifier: site\n    label:\n      en: Google Translate Site\n      zh: 翻译站点\n    type: multiple\n    values:\n      - translate.google.com\n      - translate.google.cn\n      - translate.google.com.hk\n      - translate.google.co.jp\n      - translate.google.co.uk\n    value labels:\n      - Global (translate.google.com)\n      - China (translate.google.cn)\n      - Hong Kong (translate.google.com.hk)\n      - Japan (translate.google.co.jp)\n      - UK (translate.google.co.uk)\n    default value: translate.google.com\n\n  - identifier: target_lang\n    label:\n      en: Target Language\n      zh: 目标语言\n    type: multiple\n    values:\n      - zh-CN\n      - en\n      - ja\n      - ko\n      - fr\n      - de\n      - es\n      - ru\n    value labels:\n      - 简体中文 (zh-CN)\n      - English (en)\n      - 日本語 (ja)\n      - 한국어 (ko)\n      - Français (fr)\n      - Deutsch (de)\n      - Español (es)\n      - Русский (ru)\n    default value: zh-CN\n\nactions:\n  - title: Google Translate\n    url: https://{flyclip option site}/?sl=auto&tl={flyclip option target_lang}&text={flyclip text}&op=translate\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.hash-generator",
    name: "Hash Generator",
    nameZh: "哈希值计算",
    nameEn: "Hash Generator",
    category: "developer",
    icon: "#",
    description: "Calculate MD5 and SHA-256 hashes of selected text.",
    descriptionZh: "快速计算文本的 MD5 与 SHA-256 哈希值。",
    hasOptions: true,
    optionsCount: 1,
    type: "powershell",
    configYaml: "name:\n  en: Hash Generator\n  zh-CN: 哈希值计算\ndescription:\n  en: Calculate MD5 and SHA-256 hashes of selected text.\n  zh-CN: 快速计算文本的 MD5 与 SHA-256 哈希值。\nidentifier: com.flyclip.extension.hash-generator\nicon: \"#\"\noptions:\n  - identifier: uppercase\n    label:\n      en: Output Uppercase Hex\n      zh: 输出大写十六进制\n    type: boolean\n    default value: false\n\nactions:\n  - title: MD5\n    identifier: md5\n    shell script: |\n      $bytes = [System.Text.Encoding]::UTF8.GetBytes($env:FLYCLIP_TEXT)\n      $md5 = [System.Security.Cryptography.MD5]::Create().ComputeHash($bytes)\n      $hex = [BitConverter]::ToString($md5).Replace('-', '')\n      if ($env:FLYCLIP_OPTION_UPPERCASE -ne \"1\") { $hex = $hex.ToLower() }\n      Write-Host -NoNewline $hex\n    requirements: [text]\n    after: paste-result\n\n  - title: SHA256\n    identifier: sha256\n    shell script: |\n      $bytes = [System.Text.Encoding]::UTF8.GetBytes($env:FLYCLIP_TEXT)\n      $sha = [System.Security.Cryptography.SHA256]::Create().ComputeHash($bytes)\n      $hex = [BitConverter]::ToString($sha).Replace('-', '')\n      if ($env:FLYCLIP_OPTION_UPPERCASE -ne \"1\") { $hex = $hex.ToLower() }\n      Write-Host -NoNewline $hex\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.html-encode",
    name: "HTML Encode",
    nameZh: "HTML 实体转义",
    nameEn: "HTML Encode",
    category: "text_tools",
    icon: "<&>",
    description: "Encode or decode HTML special character entities.",
    descriptionZh: "HTML 特殊实体符号转义与反转义。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: HTML Encode\n  zh-CN: HTML 实体转义\ndescription:\n  en: Encode or decode HTML special character entities.\n  zh-CN: HTML 特殊实体符号转义与反转义。\nidentifier: com.flyclip.extension.html-encode\nicon: <&>\nactions:\n  - title: HTML 转义\n    identifier: encode\n    javascript: |\n      return flyclip.input.text\n        .replace(/&/g, '&amp;')\n        .replace(/</g, '&lt;')\n        .replace(/>/g, '&gt;')\n        .replace(/\"/g, '&quot;')\n        .replace(/'/g, '&#039;');\n    requirements: [text]\n    after: paste-result\n\n  - title: HTML 反转义\n    identifier: decode\n    javascript: |\n      return flyclip.input.text\n        .replace(/&amp;/g, '&')\n        .replace(/&lt;/g, '<')\n        .replace(/&gt;/g, '>')\n        .replace(/&quot;/g, '\"')\n        .replace(/&#039;/g, \"'\")\n        .replace(/&#39;/g, \"'\");\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.imdb",
    name: "IMDb",
    nameZh: "IMDb 影视资料",
    nameEn: "IMDb",
    category: "shopping",
    icon: "iconify:simple-icons:imdb",
    description: "Search movies, TV shows, and cast on IMDb.",
    descriptionZh: "在 IMDb 数据库搜索电影、剧集与演员资料。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: IMDb\n  zh-CN: IMDb 影视资料\ndescription:\n  en: Search movies, TV shows, and cast on IMDb.\n  zh-CN: 在 IMDb 数据库搜索电影、剧集与演员资料。\nidentifier: com.flyclip.extension.imdb\nicon: iconify:simple-icons:imdb\nactions:\n  - title: IMDb\n    url: https://www.imdb.com/find?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.ip-lookup",
    name: "IP Lookup",
    nameZh: "IP 归属地查询",
    nameEn: "IP Lookup",
    category: "developer",
    icon: "IP",
    description: "Query IP address geolocation and WHOIS info.",
    descriptionZh: "查询 IP 地址的地理位置、归属地与网络 ASN 信息。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: IP Lookup\n  zh-CN: IP 归属地查询\ndescription:\n  en: Query IP address geolocation and WHOIS info.\n  zh-CN: 查询 IP 地址的地理位置、归属地与网络 ASN 信息。\nidentifier: com.flyclip.extension.ip-lookup\nicon: IP\noptions:\n  - identifier: provider\n    label:\n      en: Lookup Service\n      zh: 查询平台\n    type: multiple\n    values:\n      - ipinfo\n      - ip138\n      - bgp\n    value labels:\n      - IPInfo.io (Global)\n      - IP138 (中国地区精准)\n      - BGP Toolkit (HE.net ASN)\n    default value: ipinfo\n\nactions:\n  - title: IP 查询\n    identifier: lookup_ipinfo\n    requirements: [text]\n    url: https://ipinfo.io/{flyclip text}"
  },
  {
    id: "com.flyclip.extension.jd-search",
    name: "JD Search",
    nameZh: "京东搜索",
    nameEn: "JD Search",
    category: "shopping",
    icon: "iconify:simple-icons:jd",
    description: "Search products on JD.com.",
    descriptionZh: "在京东商城搜索选中的商品与数码好物。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: JD Search\n  zh-CN: 京东搜索\ndescription:\n  en: Search products on JD.com.\n  zh-CN: 在京东商城搜索选中的商品与数码好物。\nidentifier: com.flyclip.extension.jd-search\nicon: iconify:simple-icons:jd\nactions:\n  - title: 京东\n    url: https://search.jd.com/Search?keyword=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.join-lines",
    name: "Join Lines",
    nameZh: "多行合并为单行",
    nameEn: "Join Lines",
    category: "text_tools",
    icon: "->",
    description: "Join multi-line text into a single line with custom delimiters.",
    descriptionZh: "多行合并为单行，支持指定逗号、空格、分号等分隔符。",
    hasOptions: true,
    optionsCount: 1,
    type: "js",
    configYaml: "name:\n  en: Join Lines\n  zh-CN: 多行合并为单行\ndescription:\n  en: Join multi-line text into a single line with custom delimiters.\n  zh-CN: 多行合并为单行，支持指定逗号、空格、分号等分隔符。\nidentifier: com.flyclip.extension.join-lines\nicon: ->\noptions:\n  - identifier: delimiter\n    label:\n      en: Delimiter\n      zh: 分隔符类型\n    type: multiple\n    values:\n      - comma_space\n      - comma\n      - space\n      - semicolon\n    value labels:\n      - 逗号空格 (\", \")\n      - 纯逗号 (\",\")\n      - 空格 (\" \")\n      - 分号 (\"; \")\n    default value: comma_space\n\nactions:\n  - title: 合并为单行\n    identifier: join\n    javascript: |\n      const lines = flyclip.input.text.split(/\\r\\n|\\r|\\n/).filter(l => l.trim().length > 0);\n      const delimMap = {\n        comma: \",\",\n        space: \" \",\n        semicolon: \"; \",\n        comma_space: \", \"\n      };\n      const delim = delimMap[flyclip.options.delimiter] || \", \";\n      return lines.join(delim);\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.json-formatter",
    name: "JSON Formatter",
    nameZh: "JSON 格式化",
    nameEn: "JSON Formatter",
    category: "text_tools",
    icon: "{}",
    description: "Prettify or minify JSON text in place.",
    descriptionZh: "JSON 格式化美化排版或单行压缩。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: JSON Formatter\n  zh-CN: JSON 格式化\ndescription:\n  en: Prettify or minify JSON text in place.\n  zh-CN: JSON 格式化美化排版或单行压缩。\nidentifier: com.flyclip.extension.json-formatter\nicon: \"{}\"\nactions:\n  - title: 格式化 JSON\n    identifier: format\n    javascript: |\n      try {\n        const obj = JSON.parse(flyclip.input.text);\n        return JSON.stringify(obj, null, 2);\n      } catch (e) {\n        return \"[JSON 解析失败: 语法格式有误]\";\n      }\n    requirements: [text]\n    after: paste-result\n\n  - title: 压缩 JSON\n    identifier: minify\n    javascript: |\n      try {\n        const obj = JSON.parse(flyclip.input.text);\n        return JSON.stringify(obj);\n      } catch (e) {\n        return \"[JSON 解析失败: 语法格式有误]\";\n      }\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.markdown-tools",
    name: "Markdown Tools",
    nameZh: "Markdown 格式化",
    nameEn: "Markdown Tools",
    category: "text_tools",
    icon: "MD",
    description: "Wrap text in Markdown bold, inline code, code blocks, or blockquotes.",
    descriptionZh: "快速为选中文本添加 Markdown 粗体、行内代码、代码块或引用标记。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Markdown Tools\n  zh-CN: Markdown 格式化\ndescription:\n  en: Wrap text in Markdown bold, inline code, code blocks, or blockquotes.\n  zh-CN: 快速为选中文本添加 Markdown 粗体、行内代码、代码块或引用标记。\nidentifier: com.flyclip.extension.markdown-tools\nicon: MD\nactions:\n  - title: 粗体 (**text**)\n    identifier: bold\n    javascript: return `**${flyclip.input.text}**`;\n    requirements: [text]\n    after: paste-result\n\n  - title: 行内代码 (`code`)\n    identifier: inline_code\n    javascript: return `\\`${flyclip.input.text}\\``;\n    requirements: [text]\n    after: paste-result\n\n  - title: 代码块 (```code```)\n    identifier: code_block\n    javascript: return \"```\\n\" + flyclip.input.text + \"\\n```\";\n    requirements: [text]\n    after: paste-result\n\n  - title: 引用 (> quote)\n    identifier: quote\n    javascript: |\n      return flyclip.input.text\n        .split(/\\r\\n|\\r|\\n/)\n        .map(line => `> ${line}`)\n        .join(\"\\n\");\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.mdn-web-docs",
    name: "MDN Web Docs",
    nameZh: "MDN 开发者文档",
    nameEn: "MDN Web Docs",
    category: "translation",
    icon: "MDN",
    description: "Search web APIs, HTML, CSS, and JS reference docs on MDN.",
    descriptionZh: "搜索 MDN Web Docs 权威开发者文档与 API 规范。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: MDN Web Docs\n  zh-CN: MDN 开发者文档\ndescription:\n  en: Search web APIs, HTML, CSS, and JS reference docs on MDN.\n  zh-CN: 搜索 MDN Web Docs 权威开发者文档与 API 规范。\nidentifier: com.flyclip.extension.mdn-web-docs\nicon: MDN\noptions:\n  - identifier: locale\n    label:\n      en: Documentation Locale\n      zh: 文档语言\n    type: multiple\n    values:\n      - zh-CN\n      - en-US\n      - ja\n      - fr\n      - es\n    value labels:\n      - 简体中文 (zh-CN)\n      - English (en-US)\n      - 日本語 (ja)\n      - Français (fr)\n      - Español (es)\n    default value: zh-CN\n\nactions:\n  - title: MDN\n    url: https://developer.mozilla.org/{flyclip option locale}/search?q={flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.pot-desktop",
    name: "Pot Translate",
    nameZh: "Pot 划词翻译",
    nameEn: "Pot Translate",
    category: "translation",
    icon: "iconify:simple-icons:googletranslate",
    description: "Send selected text to Pot Desktop via local HTTP API for instant translation/OCR.",
    descriptionZh: "通过本地 HTTP 服务将选中文本发送至 Pot Desktop 进行划词翻译或 OCR。",
    hasOptions: true,
    optionsCount: 2,
    type: "js",
    configYaml: "name:\n  en: Pot Translate\n  zh-CN: Pot 划词翻译\ndescription:\n  en: Send selected text to Pot Desktop via local HTTP API for instant translation/OCR.\n  zh-CN: 通过本地 HTTP 服务将选中文本发送至 Pot Desktop 进行划词翻译或 OCR。\nidentifier: com.flyclip.extension.pot-desktop\nicon: iconify:simple-icons:googletranslate\noptions:\n  - identifier: port\n    label: Pot 本地服务端口\n    type: string\n    default value: \"60828\"\n  - identifier: action_type\n    label: 触发模式\n    type: multiple\n    values: [translate, ocr, recognize]\n    value labels: [翻译 (Translate), 截图 OCR, 文本识别]\n    default value: translate\n\nactions:\n  - title: Pot 翻译\n    javascript: |\n      const text = flyclip.input.text.trim();\n      const port = flyclip.options.port || \"60828\";\n      const action = flyclip.options.action_type || \"translate\";\n\n      // 官方标准 API：POST / 或 POST /translate (Body 为待翻译纯文本)\n      try {\n        if (action === \"ocr\") {\n          await flyclip.fetch(`http://127.0.0.1:${port}/ocr_recognize`);\n        } else if (action === \"recognize\") {\n          await flyclip.fetch(`http://127.0.0.1:${port}/ocr_translate`);\n        } else {\n          await flyclip.fetch(`http://127.0.0.1:${port}/`, {\n            method: \"POST\",\n            body: text\n          });\n        }\n      } catch (e) {\n        try {\n          await flyclip.fetch(`http://127.0.0.1:${port}/selection_translate`);\n        } catch (_) {\n          flyclip.run(\"cmd\", [\"/c\", \"start\", `pot:translate?text=${encodeURIComponent(text)}`]);\n        }\n      }\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.regex101",
    name: "Regex101",
    nameZh: "Regex101 正则测试",
    nameEn: "Regex101",
    category: "developer",
    icon: ".*",
    description: "Test and debug regular expressions in Regex101.",
    descriptionZh: "在 Regex101 中测试并分析正则表达式。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Regex101\n  zh-CN: Regex101 正则测试\ndescription:\n  en: Test and debug regular expressions in Regex101.\n  zh-CN: 在 Regex101 中测试并分析正则表达式。\nidentifier: com.flyclip.extension.regex101\nicon: \".*\"\noptions:\n  - identifier: flavor\n    label:\n      en: Regex Engine Flavor\n      zh: 正则引擎分支\n    type: multiple\n    values:\n      - pcre2\n      - javascript\n      - python\n      - golang\n      - rust\n    value labels:\n      - PCRE2\n      - JavaScript\n      - Python\n      - Golang\n      - Rust\n    default value: pcre2\n\nactions:\n  - title: Regex101\n    url: https://regex101.com/?regex={flyclip text}&flavor={flyclip option flavor}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.remove-spaces",
    name: "Remove Spaces",
    nameZh: "清除多余空格",
    nameEn: "Remove Spaces",
    category: "text_tools",
    icon: "␣",
    description: "Collapse duplicate spaces or strip all whitespace characters.",
    descriptionZh: "消除所有多余空格或压缩连续空白字符。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Remove Spaces\n  zh-CN: 清除多余空格\ndescription:\n  en: Collapse duplicate spaces or strip all whitespace characters.\n  zh-CN: 消除所有多余空格或压缩连续空白字符。\nidentifier: com.flyclip.extension.remove-spaces\nicon: \"␣\"\nactions:\n  - title: 压缩空格\n    identifier: collapse\n    javascript: return flyclip.input.text.replace(/\\s+/g, ' ').trim();\n    requirements: [text]\n    after: paste-result\n\n  - title: 消除所有空格\n    identifier: remove_all\n    javascript: return flyclip.input.text.replace(/\\s+/g, '');\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.iconify-search",
    name: "Iconify Icons",
    nameZh: "Iconify 矢量图标",
    nameEn: "Iconify Icons",
    category: "developer",
    icon: "iconify:simple-icons:iconify",
    description: "Search 200,000+ open source vector icons on Iconify.",
    descriptionZh: "在 Iconify 搜索超过 20 万个开源矢量图标与 SVG 代码。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Iconify Icons\n  zh-CN: Iconify 矢量图标\ndescription:\n  en: Search 200,000+ open source vector icons on Iconify.\n  zh-CN: 在 Iconify 搜索超过 20 万个开源矢量图标与 SVG 代码。\nidentifier: com.flyclip.extension.iconify-search\nicon: iconify:simple-icons:iconify\nactions:\n  - title: Iconify\n    url: https://icon-sets.iconify.design/?query=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.sort-lines",
    name: "Sort Lines",
    nameZh: "文本行排序与去重",
    nameEn: "Sort Lines",
    category: "text_tools",
    icon: "AZ",
    description: "Sort lines ascending, descending, or remove duplicate lines.",
    descriptionZh: "多行文本升序、降序排序与行去重。",
    hasOptions: true,
    optionsCount: 1,
    type: "js",
    configYaml: "name:\n  en: Sort Lines\n  zh-CN: 文本行排序与去重\ndescription:\n  en: Sort lines ascending, descending, or remove duplicate lines.\n  zh-CN: 多行文本升序、降序排序与行去重。\nidentifier: com.flyclip.extension.sort-lines\nicon: AZ\noptions:\n  - identifier: case_sensitive\n    label:\n      en: Case Sensitive Sort\n      zh: 区分大小写\n    type: boolean\n    default value: false\n\nactions:\n  - title: 升序排序 (A-Z)\n    identifier: sort_asc\n    javascript: |\n      const cs = flyclip.options.case_sensitive === \"1\" || flyclip.options.case_sensitive === true;\n      const lines = flyclip.input.text.split(/\\r\\n|\\r|\\n/);\n      lines.sort((a, b) => cs ? a.localeCompare(b, undefined, { sensitivity: 'case' }) : a.localeCompare(b));\n      return lines.join(\"\\n\");\n    requirements: [text]\n    after: paste-result\n\n  - title: 降序排序 (Z-A)\n    identifier: sort_desc\n    javascript: |\n      const cs = flyclip.options.case_sensitive === \"1\" || flyclip.options.case_sensitive === true;\n      const lines = flyclip.input.text.split(/\\r\\n|\\r|\\n/);\n      lines.sort((a, b) => cs ? b.localeCompare(a, undefined, { sensitivity: 'case' }) : b.localeCompare(a));\n      return lines.join(\"\\n\");\n    requirements: [text]\n    after: paste-result\n\n  - title: 行去重 (Unique)\n    identifier: unique\n    javascript: |\n      const cs = flyclip.options.case_sensitive === \"1\" || flyclip.options.case_sensitive === true;\n      const lines = flyclip.input.text.split(/\\r\\n|\\r|\\n/);\n      if (cs) {\n        return Array.from(new Set(lines)).join(\"\\n\");\n      } else {\n        const seen = new Set();\n        const result = [];\n        for (const line of lines) {\n          const lower = line.toLowerCase();\n          if (!seen.has(lower)) {\n            seen.add(lower);\n            result.push(line);\n          }\n        }\n        return result.join(\"\\n\");\n      }\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.stranslate",
    name: "STranslate",
    nameZh: "STranslate 翻译",
    nameEn: "STranslate",
    category: "translation",
    icon: "ST",
    description: "Trigger Windows open-source STranslate tool for deep translation.",
    descriptionZh: "通过本地服务或命令行调用 Windows 开源神器 STranslate 进行即时翻译。",
    hasOptions: true,
    optionsCount: 2,
    type: "js",
    configYaml: "name:\n  en: STranslate\n  zh-CN: STranslate 翻译\ndescription:\n  en: Trigger Windows open-source STranslate tool for deep translation.\n  zh-CN: 通过本地服务或命令行调用 Windows 开源神器 STranslate 进行即时翻译。\nidentifier: com.flyclip.extension.stranslate\nicon: ST\nplatforms: [windows] # 明确标记 Windows 平台，方便多设备 WebDAV 同步时按需启用\noptions:\n  - identifier: trigger_mode\n    label: 唤起方式\n    type: multiple\n    values: [http, cli]\n    value labels: [本地 HTTP 服务, 命令行 CLI 唤起]\n    default value: http\n  - identifier: port\n    label: HTTP 服务端口\n    type: string\n    default value: \"50020\"\n\nactions:\n  - title: STranslate\n    javascript: |\n      const text = flyclip.input.text.trim();\n      const mode = flyclip.options.trigger_mode || \"http\";\n      const port = flyclip.options.port || \"50020\";\n\n      if (mode === \"http\") {\n        try {\n          await flyclip.fetch(`http://127.0.0.1:${port}/translate_force`, {\n            method: \"POST\",\n            body: text\n          });\n        } catch (e) {\n          flyclip.run(\"STranslate\", [\"-t\", text]);\n        }\n      } else {\n        flyclip.run(\"STranslate\", [\"-t\", text]);\n      }\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.taobao-search",
    name: "Taobao Search",
    nameZh: "淘宝搜索",
    nameEn: "Taobao Search",
    category: "shopping",
    icon: "iconify:simple-icons:taobao",
    description: "Search items and deals on Taobao.",
    descriptionZh: "在淘宝网搜索选中的商品宝贝与优惠。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Taobao Search\n  zh-CN: 淘宝搜索\ndescription:\n  en: Search items and deals on Taobao.\n  zh-CN: 在淘宝网搜索选中的商品宝贝与优惠。\nidentifier: com.flyclip.extension.taobao-search\nicon: iconify:simple-icons:taobao\nactions:\n  - title: 淘宝\n    url: https://s.taobao.com/search?q=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.text-statistics",
    name: "Text Statistics",
    nameZh: "字数与文本统计",
    nameEn: "Text Statistics",
    category: "text_tools",
    icon: "123",
    description: "Count characters, words, lines, and bytes in selected text.",
    descriptionZh: "实时统计字符数、词数、行数与字节大小并展示于提示栏。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Text Statistics\n  zh-CN: 字数与文本统计\ndescription:\n  en: Count characters, words, lines, and bytes in selected text.\n  zh-CN: 实时统计字符数、词数、行数与字节大小并展示于提示栏。\nidentifier: com.flyclip.extension.text-statistics\nicon: 123\nactions:\n  - title: 字数统计\n    identifier: stats\n    javascript: |\n      const t = flyclip.input.text;\n      const chars = t.length;\n      const words = (t.match(/\\S+/g) || []).length;\n      const lines = t.split(/\\r\\n|\\r|\\n/).length;\n      const bytes = new TextEncoder().encode(t).length;\n      return `${chars} 字符 · ${words} 词 · ${lines} 行 · ${bytes} B`;\n    requirements: [text]\n    after: show-result"
  },
  {
    id: "com.flyclip.extension.timestamp-converter",
    name: "Timestamp Converter",
    nameZh: "时间戳转换",
    nameEn: "Timestamp Converter",
    category: "text_tools",
    icon: "⏱️",
    description: "Convert Unix epoch timestamps to local date-time strings.",
    descriptionZh: "Unix 时间戳转换为本地日期时间，或获取当前秒级时间戳。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: Timestamp Converter\n  zh-CN: 时间戳转换\ndescription:\n  en: Convert Unix epoch timestamps to local date-time strings.\n  zh-CN: Unix 时间戳转换为本地日期时间，或获取当前秒级时间戳。\nidentifier: com.flyclip.extension.timestamp-converter\nicon: ⏱️\nactions:\n  - title: 时间戳转日期 (To Date)\n    identifier: to_date\n    javascript: |\n      const s = flyclip.input.text.trim();\n      if (/^\\d{10}$/.test(s)) {\n        const d = new Date(parseInt(s, 10) * 1000);\n        return d.getFullYear() + '-' +\n          String(d.getMonth() + 1).padStart(2, '0') + '-' +\n          String(d.getDate()).padStart(2, '0') + ' ' +\n          String(d.getHours()).padStart(2, '0') + ':' +\n          String(d.getMinutes()).padStart(2, '0') + ':' +\n          String(d.getSeconds()).padStart(2, '0');\n      } else if (/^\\d{13}$/.test(s)) {\n        const d = new Date(parseInt(s, 10));\n        return d.getFullYear() + '-' +\n          String(d.getMonth() + 1).padStart(2, '0') + '-' +\n          String(d.getDate()).padStart(2, '0') + ' ' +\n          String(d.getHours()).padStart(2, '0') + ':' +\n          String(d.getMinutes()).padStart(2, '0') + ':' +\n          String(d.getSeconds()).padStart(2, '0') + '.' +\n          String(d.getMilliseconds()).padStart(3, '0');\n      } else {\n        return \"[无效的时间戳: 需为 10 位秒级或 13 位毫秒级数字]\";\n      }\n    requirements: [text]\n    after: paste-result\n\n  - title: 当前时间戳 (Now)\n    identifier: now\n    javascript: return Math.floor(Date.now() / 1000).toString();\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.urban-dictionary",
    name: "Urban Dictionary",
    nameZh: "Urban 俚语词典",
    nameEn: "Urban Dictionary",
    category: "translation",
    icon: "UD",
    description: "Look up slang and idioms on Urban Dictionary.",
    descriptionZh: "在 Urban Dictionary 查询英语流行俚语与俗语含义。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Urban Dictionary\n  zh-CN: Urban 俚语词典\ndescription:\n  en: Look up slang and idioms on Urban Dictionary.\n  zh-CN: 在 Urban Dictionary 查询英语流行俚语与俗语含义。\nidentifier: com.flyclip.extension.urban-dictionary\nicon: UD\nactions:\n  - title: Urban Dict\n    url: https://www.urbandictionary.com/define.php?term={flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.url-encode",
    name: "URL Encode",
    nameZh: "URL 编解码",
    nameEn: "URL Encode",
    category: "text_tools",
    icon: "%20",
    description: "Percent-encode and decode URL parameters.",
    descriptionZh: "URL 百分号编码与反向解码。",
    hasOptions: false,
    
    type: "js",
    configYaml: "name:\n  en: URL Encode\n  zh-CN: URL 编解码\ndescription:\n  en: Percent-encode and decode URL parameters.\n  zh-CN: URL 百分号编码与反向解码。\nidentifier: com.flyclip.extension.url-encode\nicon: \"%20\"\nactions:\n  - title: URL 编码\n    identifier: encode\n    javascript: return encodeURIComponent(flyclip.input.text);\n    requirements: [text]\n    after: paste-result\n\n  - title: URL 解码\n    identifier: decode\n    javascript: |\n      try {\n        return decodeURIComponent(flyclip.input.text);\n      } catch (e) {\n        return flyclip.input.text;\n      }\n    requirements: [text]\n    after: paste-result"
  },
  {
    id: "com.flyclip.extension.wikipedia",
    name: "Wikipedia",
    nameZh: "维基百科",
    nameEn: "Wikipedia",
    category: "translation",
    icon: "iconify:simple-icons:wikipedia",
    description: "Search Wikipedia encyclopedia in multiple languages.",
    descriptionZh: "在维基百科中搜索选中文本词条。",
    hasOptions: true,
    optionsCount: 1,
    type: "url",
    configYaml: "name:\n  en: Wikipedia\n  zh-CN: 维基百科\ndescription:\n  en: Search Wikipedia encyclopedia in multiple languages.\n  zh-CN: 在维基百科中搜索选中文本词条。\nidentifier: com.flyclip.extension.wikipedia\nicon: iconify:simple-icons:wikipedia\noptions:\n  - identifier: lang\n    label:\n      en: Language Edition\n      zh: 语言版本\n    type: multiple\n    values:\n      - zh\n      - en\n      - ja\n      - de\n      - fr\n      - es\n      - ru\n    value labels:\n      - 中文 (zh)\n      - English (en)\n      - 日本語 (ja)\n      - Deutsch (de)\n      - Français (fr)\n      - Español (es)\n      - Русский (ru)\n    default value: zh\n\nactions:\n  - title: Wikipedia\n    url: https://{flyclip option lang}.wikipedia.org/wiki/{flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.youdao-dict",
    name: "Youdao Dictionary",
    nameZh: "有道词典",
    nameEn: "Youdao Dictionary",
    category: "translation",
    icon: "有道",
    description: "Look up words in Youdao Dictionary.",
    descriptionZh: "有道词典划词查词与权威翻译释义。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Youdao Dictionary\n  zh-CN: 有道词典\ndescription:\n  en: Look up words in Youdao Dictionary.\n  zh-CN: 有道词典划词查词与权威翻译释义。\nidentifier: com.flyclip.extension.youdao-dict\nicon: 有道\nactions:\n  - title: 有道词典\n    url: https://dict.youdao.com/search?q={flyclip text}\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.youtube-search",
    name: "YouTube Search",
    nameZh: "YouTube",
    nameEn: "YouTube Search",
    category: "search_ai",
    icon: "iconify:simple-icons:youtube",
    description: "Search videos on YouTube.",
    descriptionZh: "在 YouTube 上搜索全球精彩视频。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: YouTube Search\n  zh-CN: YouTube\ndescription:\n  en: Search videos on YouTube.\n  zh-CN: 在 YouTube 上搜索全球精彩视频。\nidentifier: com.flyclip.extension.youtube-search\nicon: iconify:simple-icons:youtube\nactions:\n  - title: YouTube\n    url: https://www.youtube.com/results?search_query=***\n    requirements: [text]"
  },
  {
    id: "com.flyclip.extension.zhihu-search",
    name: "Zhihu Search",
    nameZh: "知乎搜索",
    nameEn: "Zhihu Search",
    category: "search_ai",
    icon: "iconify:simple-icons:zhihu",
    description: "Search questions and discussions on Zhihu.",
    descriptionZh: "在知乎搜索相关问题、高赞回答与专栏文章。",
    hasOptions: false,
    
    type: "url",
    configYaml: "name:\n  en: Zhihu Search\n  zh-CN: 知乎搜索\ndescription:\n  en: Search questions and discussions on Zhihu.\n  zh-CN: 在知乎搜索相关问题、高赞回答与专栏文章。\nidentifier: com.flyclip.extension.zhihu-search\nicon: iconify:simple-icons:zhihu\nactions:\n  - title: 知乎\n    url: https://www.zhihu.com/search?type=content&q=***\n    requirements: [text]"
  },
];
